### PR TITLE
Page Objects for Opportunities

### LINKED ISSUE #17: Create page objects for Opportunities
Create page objects that can be used at the moment to test the actions create, edit, delete opportunities.

PageObjects:
- Opportunities (Main page)
- OpportunityView
- OpportunityDetails

### PR DESCRIPTION
**Pull request by acamacho82**
Fixes #17

I tried to add all needed page objects and locators to add, edit, delete Opportunities.

I also refactored the BasicNewItemForm, it was renamed to BasicForm and it is an abstract class where the method setDataInFormFields must to be implemented for each child form, see the class OpportunityForm.java

### CODE REVIEW

**Review by mfuentes-ME — COMMENTED** [review]
I am getting an error with  AssetsPage.java

**Comment by edgarquispe** [comment]
Yes the same, looks like AssetsPage.java  is already unusable.

**Comment by mfuentes-ME** [comment]
To get working the dependency injection you need to add the following to dependency on build.gradle
testCompile group: 'io.cucumber', name: 'cucumber-picocontainer', version: '4.4.0'

**Review by mfuentes-ME — APPROVED** [review]
It is working fine.

**Pull request merged**
